- theme_overrides/base.html
> Clarify that docs website is based on master

- src/ExceptionHandler.php
> Revert "Remove usage of \JSON_THROW_ON_ERROR"

- src/OnlineChecker.php
Aside: There are both tabs and spaces used for indentation. Setting up phpcbf and/or editorconfig may help standardize this?
> Allow different whitespace for taintAnalysis

- assets/articles/getting-ready-for-named-arguments.md
This can be caught.
Also, use php syntax highlighting for code blocks.
> Change "fatal error" -> "Uncaught Error"

- includes/script.php
- src/OnlineChecker.php
- views/article.php
This intend to fix #39
However, I'm pretty sure this is not working but I don't have any idea how to test this.
> Implement psalter

- codes.sql
- db/migrations/20210701061144_add_use_phpdoc_without_magic_call_field.php
- includes/script.php
- src/OnlineChecker.php
- views/add_code.php
- views/article.php
- views/index.php
- views/snippet.php
> Add use_phpdoc_without_magic_call setting

- Dockerfile
This is required for composer to work
Fixed psalm/psalm.dev#57
> Install unzip and git into apache container

- codes.sql
- db/migrations/20210701160045_add_restrict_return_types_field.php
- views/add_code.php
- views/index.php
- views/snippet.php
> Add restrict_return_types setting field

- views/check.php
> Return HTTP 500 if OnlineChecker fails

- src/OnlineChecker.php
> Use `FakeFileProvider` from `vendor/vimeo/psalm/src`

- includes/script.php
> Open sandbox links in a new tab

- src/OnlineChecker.php
This is due to Psalm internal API change in vimeo/psalm#7006
> Set PHP version source

- src/OnlineChecker.php
- views/snippet.php
It already defaults to 8.1 in interactive sandbox
> Update default PHP version to 8.1

- includes/script.php
> Fix taint trace highlighting

- assets/articles/psalm-5.md
This won't yet be visible on the site
> Psalm 5 announcement post

- includes/script.php
- src/OnlineChecker.php
- views/add_code.php
- views/article.php
- views/index.php
- views/snippet.php
> Remove `allow_phpstorm_generics`

- src/OnlineChecker.php
- views/check.php
- views/snippet.php
And use a single constant instead of hardcoding the default version in
several places
> Use PHP 8.2 by default

- includes/script.php
goal: simplify latest changes check
Similar to [Rector](https://getrector.com/demo/22c0fb81-c6cb-49bd-8850-87f928f7b0be), that also have "Create issue" and "Create test" buttons (WDYT about using similar ones)
> Use a link to the latest commit

- src/OnlineChecker.php
Fixes compatibility with nikic/php-parser:5
> Drop unused vars

- db/migrations/20240226043924_add_ensure_override_attribute.php
- includes/script.php
- src/OnlineChecker.php
- src/Settings.php
- views/add_code.php
- views/article.php
- views/index.php
- views/snippet.php
Also:
- centralize the list of available settings into a single place
- fix `Fix code` button to use HTTP locally
> Add `ensure_override_attribute` toggle
